In [3]:
import pandas as pd
import numpy as np

df = pd.read_excel('Pivot.xlsx')
df.head()

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06

In [2]:
df.pivot_table(values='Sprzedaż',index='Przedstawiciel',columns='Region',aggfunc=np.sum)

Region          Południe   Wschód   Zachód  ZachódCentrum
Przedstawiciel
Franciszek       3029.98  8919.85  1608.96            NaN
Grzegorz         2040.69  4854.15  4376.02         154.34
Krystian         2228.68  7894.56  2006.31            NaN
Patryk           5769.22  5670.96  2828.02         816.84
Paulina          1954.58  6696.10  9790.96        1449.21
Szymon           4791.80  3633.19  4168.15            NaN

In [4]:
df.pivot_table(values='Sprzedaż',index='Przedstawiciel',columns='Region',aggfunc=np.sum).fillna(0).round(2)

Region          Południe   Wschód   Zachód  ZachódCentrum
Przedstawiciel
Franciszek       3029.98  8919.85  1608.96           0.00
Grzegorz         2040.69  4854.15  4376.02         154.34
Krystian         2228.68  7894.56  2006.31           0.00
Patryk           5769.22  5670.96  2828.02         816.84
Paulina          1954.58  6696.10  9790.96        1449.21
Szymon           4791.80  3633.19  4168.15           0.00

In [7]:
df.pivot_table(values='Sprzedaż',index=['Region','Przedstawiciel', ],aggfunc=np.sum).round(2)

                              Sprzedaż
Region        Przedstawiciel
Południe      Franciszek       3029.98
              Grzegorz         2040.69
              Krystian         2228.68
              Patryk           5769.22
              Paulina          1954.58
              Szymon           4791.80
Wschód        Franciszek       8919.85
              Grzegorz         4854.15
              Krystian         7894.56
              Patryk           5670.96
              Paulina          6696.10
              Szymon           3633.19
Zachód        Franciszek       1608.96
              Grzegorz         4376.02
              Krystian         2006.31
              Patryk           2828.02
              Paulina          9790.96
              Szymon           4168.15
ZachódCentrum Grzegorz          154.34
              Patryk            816.84
              Paulina          1449.21

In [8]:
df.pivot_table(values='Sprzedaż',index='Region',aggfunc=[len,np.max,np.min]).round(0)

                   len      max      min
              Sprzedaż Sprzedaż Sprzedaż
Region
Południe            27   1512.0    115.0
Wschód              50   1675.0    153.0
Zachód              24   5001.0    132.0
ZachódCentrum        4   1449.0    154.0

In [10]:
def commission_fee(x):


    if x <= 300:
        return 0
    elif x <= 900:
        return x * 0.03
    else:
        return x * 0.06

In [18]:
df['commission_fee'] = df['Sprzedaż'].apply(lambda x: commission_fee(x))
df.head()

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,12.9651
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666

In [21]:
df['Produkt_len'] = df['Produkt'].apply(len)
df.head()

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,12.9651,4
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550,6
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213,4
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562,6
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666,8

In [23]:
import math
df['#_opakowań'] = df['Sztuki'].apply(lambda x: math.ceil(x/5))
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowań
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,12.9651,4,4
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550,6,5
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213,4,6
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562,6,4
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666,8,8
...,...,...,...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16,66.0084,6,10
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57,0.0000,4,2
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,13.1343,8,5
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,20.2725,4,5
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,55.8894,8,10

In [24]:
def bonus(row):

    margin = (row['Sprzedaż'] - row['Koszty'])/row['Sprzedaż']

    if margin > 0.55:
        return 200
    else:
        return 0

In [25]:
df['Bonus'] = df.apply(lambda row: bonus(row),axis=1)
df.sample(10)

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowań,Bonus
87,2020-01-26,Bellen,Wschód,Grzegorz,PSA,21,462.17,210.81,13.8651,6,5,0
27,2020-01-10,Sunset,Wschód,Grzegorz,TRU,27,567.18,250.66,17.0154,6,6,200
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,20.2725,4,5,0
40,2020-01-13,Bellen,Wschód,Paulina,PLOT,57,1254.57,570.77,75.2742,6,12,0
69,2020-01-21,Sunshine,Wschód,Paulina,DFR,23,437.92,184.33,13.1376,8,5,200
58,2020-01-18,Sunset,Wschód,Grzegorz,MNGD,12,252.44,111.66,0.0000,6,3,200
68,2020-01-21,Quad,Wschód,Krystian,FM,58,1566.83,841.43,94.0098,4,12,0
17,2020-01-07,Sunset,Wschód,Szymon,PCC,22,462.22,203.57,13.8666,6,5,200
29,2020-01-10,Quad,ZachódCentrum,Patryk,DFR,17,459.29,246.75,13.7787,4,4,0
90,2020-01-27,Carlota,Zachód,Grzegorz,QT,10,230.25,110.43,0.0000,7,2,0

In [27]:
car_dict = dict(zip(df['Przedstawiciel'].unique(),['Mazda','Toyota','BMW','Audi','Fiat','Seat']))
car_dict

{'Szymon': 'Mazda',
 'Grzegorz': 'Toyota',
 'Paulina': 'BMW',
 'Krystian': 'Audi',
 'Franciszek': 'Fiat',
 'Patryk': 'Seat'}

In [28]:
df['Marka_samochodu'] = df['Przedstawiciel'].map(car_dict)
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowań,Bonus,Marka_samochodu
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,12.9651,4,4,0,Mazda
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550,6,5,0,Toyota
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213,4,6,0,BMW
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562,6,4,0,BMW
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666,8,8,200,BMW
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16,66.0084,6,10,0,Audi
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57,0.0000,4,2,0,Toyota
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,13.1343,8,5,200,Mazda
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,20.2725,4,5,0,Mazda
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,55.8894,8,10,200,Toyota

In [32]:
df.map(lambda x: x.upper() if isinstance(x,str) else x)

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowań,Bonus,Marka_samochodu
0,2020-01-01,QUAD,WSCHÓD,SZYMON,AA,16,432.17,232.99,12.9651,4,4,0,MAZDA
1,2020-01-02,BELLEN,POŁUDNIE,GRZEGORZ,KBTB,24,528.50,240.35,15.8550,6,5,0,TOYOTA
2,2020-01-02,QUAD,ZACHÓD,PAULINA,AST,30,810.71,435.64,24.3213,4,6,0,BMW
3,2020-01-02,BELLEN,ZACHÓD,PAULINA,SFWK,19,418.54,190.05,12.5562,6,4,0,BMW
4,2020-01-03,SUNSHINE,WSCHÓD,PAULINA,FM,38,722.22,304.06,21.6666,8,8,200,BMW
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2020-01-29,BELLEN,WSCHÓD,KRYSTIAN,AST,50,1100.14,500.16,66.0084,6,10,0,AUDI
101,2020-01-29,QUAD,WSCHÓD,GRZEGORZ,PLOT,10,270.50,145.57,0.0000,4,2,0,TOYOTA
102,2020-01-30,SUNSHINE,POŁUDNIE,SZYMON,TTT,23,437.81,184.16,13.1343,8,5,200,MAZDA
103,2020-01-30,QUAD,POŁUDNIE,SZYMON,TTT,25,675.75,362.89,20.2725,4,5,0,MAZDA
104,2020-01-30,SUNSHINE,ZACHÓD,GRZEGORZ,DFR,49,931.49,392.84,55.8894,8,10,200,TOYOTA

In [33]:
df['Data'] = pd.to_datetime(df['Data'])
df['Data'].dt.day_name().head()

0    Wednesday
1     Thursday
2     Thursday
3     Thursday
4       Friday
Name: Data, dtype: str

In [34]:
df['Data'].dt.month_name().head()

0    January
1    January
2    January
3    January
4    January
Name: Data, dtype: str

In [35]:
df[df['Data'].dt.day_name()=='Thursday'].head()

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowań,Bonus,Marka_samochodu
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550,6,5,0,Toyota
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213,4,6,0,BMW
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562,6,4,0,BMW
22,2020-01-09,Carlota,Wschód,Franciszek,WSD,38,874.45,418.69,26.2335,7,8,0,Fiat
23,2020-01-09,Bellen,Wschód,Paulina,EPP,40,880.38,400.89,26.4114,6,8,0,BMW

In [36]:
df['Produkt'].str.upper().head()

0        QUAD
1      BELLEN
2        QUAD
3      BELLEN
4    SUNSHINE
Name: Produkt, dtype: str

In [37]:
df['Region'].str.endswith('ód').head()

0     True
1    False
2     True
3     True
4     True
Name: Region, dtype: bool

In [38]:
df[df['Region'].str.contains('Zachód')].sample(5)

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowań,Bonus,Marka_samochodu
14,2020-01-06,Carlota,Zachód,Szymon,KPSA,18,414.11,198.71,12.4233,7,4,0,Mazda
98,2020-01-28,Sunset,Zachód,Krystian,FM,62,1302.86,574.25,78.1716,6,13,200,Audi
28,2020-01-10,Carlota,ZachódCentrum,Paulina,AA,63,1449.21,693.64,86.9526,7,13,0,BMW
73,2020-01-21,Quad,Zachód,Grzegorz,ITW,56,1512.60,812.83,90.7560,4,12,0,Toyota
89,2020-01-26,Bellen,Zachód,Paulina,FRED,61,5000.60,610.16,300.0360,6,13,200,BMW