# **Zadanie: przestępczość**

Import nieszbednych bibliotek

In [10]:
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
import missingno as msno
import numpy as np

wczytanie danych z pliku csv

In [56]:
df = pd.read_csv('fatal-police-shootings-data.csv')
print(df[['race', 'date',]].isnull().sum())
df['race'] = df['race'].fillna('Unknown')
df.head()

race    521
date      0
dtype: int64

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False

In [47]:
new_df = df.pivot_table(index='race', columns='signs_of_mental_illness', aggfunc='size')

In [48]:
new_df['%_mental_illness'] = new_df.apply(lambda x: ((x[True] / (x[True] + x[False]))*100), axis=1)
new_df

signs_of_mental_illness  False  True  %_mental_illness
race
A                           69    24         25.806452
B                         1114   184         14.175655
H                          745   157         17.405765
N                           64    14         17.948718
O                           37    11         22.916667
Unknown                    408   113         21.689060
W                         1763   713         28.796446

In [53]:
print(f"Najczęściej znamiona choroby psychicznej występują w rasie: {new_df['%_mental_illness'].idxmax()} i wynoszą {new_df['%_mental_illness'].max().round(2)}%")

Najczęściej znamiona choroby psychicznej występują w rasie: W i wynoszą 28.8%

In [63]:
df['date'] = pd.to_datetime(df['date'])
df['day_of_intervention'] = df['date'].dt.day_name()
df.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,day_of_intervention
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False,Friday
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False,Friday
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False,Saturday
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False,Sunday
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False,Sunday

In [66]:
days_count = df['day_of_intervention'].value_counts()
days_count

day_of_intervention
Wednesday    829
Tuesday      816
Thursday     810
Friday       761
Sunday       753
Monday       726
Saturday     721
Name: count, dtype: int64